### ISSUE TITLE
Fail to `make manifests`

### ISSUE THREAD

**Issue by hezhizhen** [opencurve/curve-operator#10]
<img width="1088" alt="Screenshot 2023-03-14 at 14 54 34" src="https://user-images.githubusercontent.com/7611700/224919628-23b02252-0415-4651-8b0c-0d195a07b0c1.png">

**Comment by caoxianfei1** [comment]
@hezhizhen what is the version of Kubernetes? it may be blamed to controller-gen version.

**Comment by hezhizhen** [comment]
controller-gen's version is v0.8.0 . It was downloaded on 2023-02-02.

**Comment by hezhizhen** [comment]
I use `minikube` with Kubernetes v1.25.0

**Comment by caoxianfei1** [comment]
@hezhizhen you can use `make generate` to get and install controller-gen@v0.2.5 instead of v0.8.0, and try kubernetes v1.19 or v1.20 again, it should be ok.
